INSERT INTO Park VALUES 
(1,NULL,'ALB01','Riverside Park','Albany','NY','US'),
(2,NULL,'ALT01','Columbia Park','Altoona','PA','US'),
(3,'Edison Field; Anaheim Stadium','ANA01','Angel Stadium of Anaheim','Anaheim','CA','US'),
(4,NULL,'ARL01','Arlington Stadium','Arlington','TX','US'),
(5,'The Ballpark in Arlington; Ameriquest Fl','ARL02','Rangers Ballpark in Arlington','Arlington','TX','US'),
(6,NULL,'ATL01','Atlanta-Fulton County Stadium','Atlanta','GA','US'),
(7,NULL,'ATL02','Turner Field','Atlanta','GA','US'),
(8,NULL,'ATL03','Suntrust Park','Atlanta','GA','US'),
(9,NULL,'BAL01','Madison Avenue Grounds','Baltimore','MD','US'),
(10,NULL,'BAL02','Newington Park','Baltimore','MD','US'),
(11,NULL,'BAL03','Oriole Park I','Baltimore','MD','US'),
(12,NULL,'BAL04','Belair Lot','Baltimore','MD','US'),
(13,NULL,'BAL05','Monumental Park','Baltimore','MD','US'),
(14,NULL,'BAL06','Oriole Park II','Baltimore','MD','US'),
(15,NULL,'BAL07','Oriole Park III','Baltimore','MD','US'),
(16,'American League Park','BAL09','Oriole Park IV','Baltimore','MD','US'),
(17,'Oriole Park V','BAL10','Terrapin Park','Baltimore','MD','US'),
(18,NULL,'BAL11','Memorial Stadium','Baltimore','MD','US'),
(19,NULL,'BAL12','Oriole Park at Camden Yards','Baltimore','MD','US'),
(20,'Walpole Street Grounds','BOS01','South End Grounds I','Boston','MA','US'),
(21,'Union Park','BOS02','Dartmouth Grounds','Boston','MA','US'),
(22,NULL,'BOS03','South End Grounds II','Boston','MA','US'),
(23,NULL,'BOS04','Congress Street Grounds','Boston','MA','US'),
(24,NULL,'BOS05','South End Grounds III','Boston','MA','US'),
(25,NULL,'BOS06','Huntington Avenue Baseball Grounds','Boston','MA','US'),
(26,NULL,'BOS07','Fenway Park','Boston','MA','US'),
(27,'Bee Hive','BOS08','Braves Field','Boston','MA','US'),
(28,NULL,'BUF01','Riverside Grounds','Buffalo','NY','US'),
(29,NULL,'BUF02','Olympic Park I','Buffalo','NY','US'),
(30,NULL,'BUF03','Olympic Park II','Buffalo','NY','US'),
(31,'Federal League Park','BUF04','International Fair Association Grounds','Buffalo','NY','US'),
(32,'Pastime Park','CAN01','Mahaffey Park','Canton','OH','US'),
(33,NULL,'CAN02','Pastime Park','Canton','OH','US'),
(34,'Union Base-ball Grounds','CHI01','Lake Front Park I','Chicago','IL','US'),
(35,NULL,'CHI02','23rd Street Park','Chicago','IL','US'),
(36,NULL,'CHI03','Lake Front Park II','Chicago','IL','US'),
(37,'Cricket Club Grounds; Union Grounds','CHI05','South Side Park I','Chicago','IL','US'),
(38,NULL,'CHI06','West Side Park','Chicago','IL','US'),
(39,NULL,'CHI07','South Side Park II','Chicago','IL','US'),
(40,NULL,'CHI08','West Side Grounds','Chicago','IL','US'),
(41,NULL,'CHI09','South Side Park III','Chicago','IL','US'),
(42,'White Sox Park','CHI10','Comiskey Park I','Chicago','IL','US'),
(43,'Weeghman Park; Cubs Park','CHI11','Wrigley Field','Chicago','IL','US'),
(44,'U.S. Cellular Field;White Sox Park; Comiskey Park II','CHI12','Guaranteed Rate Field','Chicago','IL','US'),
(45,'Union Cricket Club Grounds','CIN01','Lincoln Park Grounds','Cincinnati','OH','US'),
(46,NULL,'CIN02','Avenue Grounds','Cincinnati','OH','US'),
(47,NULL,'CIN03','Bank Street Grounds','Cincinnati','OH','US'),
(48,NULL,'CIN04','League Park I','Cincinnati','OH','US'),
(49,NULL,'CIN05','League Park II','Cincinnati','OH','US'),
(50,'League Park III','CIN06','Palace of the Fans','Cincinnati','OH','US'),
(51,'Redland Field','CIN07','Crosley Field','Cincinnati','OH','US'),
(52,'Riverfront Stadium','CIN08','Cinergy Field','Cincinnati','OH','US'),
(53,NULL,'CIN09','Great American Ballpark','Cincinnati','OH','US'),
(54,NULL,'CLE01','National Association Grounds','Cleveland','OH','US'),
(55,'Kennard Street Park','CLE02','League Park I','Cleveland','OH','US'),
(56,'American Association Park','CLE03','League Park II','Cleveland','OH','US'),
(57,'Players League Park','CLE04','Brotherhood Park','Cleveland','OH','US'),
(58,'National League Park III','CLE05','League Park III','Cleveland','OH','US'),
(59,'Dunn Field','CLE06','League Park IV','Cleveland','OH','US'),
(60,'Municipal Stadium','CLE07','Cleveland Stadium','Cleveland','OH','US'),
(61,'Jacobs Field','CLE08','Progressive Field','Cleveland','OH','US'),
(62,NULL,'CLE09','Cedar Avenue Driving Park','Cleveland','OH','US'),
(63,NULL,'CLL01','Euclid Beach Park','Collinwood','OH','US'),
(64,NULL,'COL01','Recreation Park I','Columbus','OH','US'),
(65,NULL,'COL02','Recreation Park II','Columbus','OH','US'),
(66,NULL,'COL03','Neil Park I','Columbus','OH','US'),
(67,NULL,'COL04','Neil Park II','Columbus','OH','US'),
(68,NULL,'COV01','Star Baseball Park','Covington','KY','US'),
(69,NULL,'DAY01','Fairview Park','Dayton','OH','US'),
(70,NULL,'DEN01','Mile High Stadium','Denver','CO','US'),
(71,NULL,'DEN02','Coors Field','Denver','CO','US'),
(72,NULL,'DET01','Recreation Park','Detroit','MI','US'),
(73,NULL,'DET02','Bennett Park','Detroit','MI','US'),
(74,'West End Park','DET03','Burns Park','Detroit','MI','US'),
(75,'Navin Field; Briggs Stadium','DET04','Tiger Stadium','Detroit','MI','US'),
(76,NULL,'DET05','Comerica Park','Detroit','MI','US'),
(77,NULL,'DOV01','Fairview Park Fair Grounds','Dover','DE','US'),
(78,NULL,'ELM01','Maple Avenue Driving Park','Elmira','NY','US'),
(79,'Hamilton Field','FOR01','Grand Duchess','Fort Wayne','IN','US'),
(80,NULL,'FOR03','Jailhouse Flats','Fort Wayne','IN','US'),
(81,NULL,'FTB01','Fort Bragg Field','Fort Bragg','NC','US'),
(82,'Beyerle''s Park','GEA01','Geauga Lake Grounds','Geauga Lake','OH','US'),
(83,NULL,'GLO01','Gloucester Point Grounds','Gloucester City','NJ','US'),
(84,NULL,'GLO02','Gloucester Fireworks Park','Gloucester City','NJ','US'),
(85,NULL,'GRA01','Ramona Park','Grand Rapids','MI','US'),
(86,NULL,'HAR01','Harrison Field','Harrison','NJ','US'),
(87,NULL,'HOB01','Elysian Field','Hoboken','NJ','US'),
(88,NULL,'HON01','Aloha Stadium','Honolulu','HI','US'),
(89,NULL,'HOU01','Colt Stadium','Houston','TX','US'),
(90,NULL,'HOU02','Astrodome','Houston','TX','US'),
(91,'Enron Field; Astros Field','HOU03','Minute Maid Park','Houston','TX','US'),
(92,NULL,'HRT01','Hartford Ball Club Grounds','Hartford','CT','US'),
(93,NULL,'HRT02','Hartford Trotting Park','Hartford','CT','US'),
(94,NULL,'IND01','South Street Park','Indianapolis','IN','US'),
(95,NULL,'IND02','Seventh Street Park I','Indianapolis','IN','US'),
(96,NULL,'IND03','Bruce Grounds','Indianapolis','IN','US'),
(97,NULL,'IND04','Seventh Street Park II','Indianapolis','IN','US'),
(98,NULL,'IND05','Seventh Street Park III','Indianapolis','IN','US'),
(99,NULL,'IND06','Indianapolis Park','Indianapolis','IN','US'),
(100,'Washington Park','IND07','Federal League Park','Indianapolis','IN','US'),
(101,NULL,'IRO01','Windsor Beach','Irondequoit','NY','US'),
(102,NULL,'JER01','Oakdale Park','Jersey City','NJ','US'),
(103,NULL,'JER02','Roosevelt Stadium','Jersey City','NJ','US'),
(104,NULL,'KAN01','Athletic Park','Kansas City','MO','US'),
(105,NULL,'KAN02','Association Park','Kansas City','MO','US'),
(106,NULL,'KAN03','Exposition Park','Kansas City','MO','US'),
(107,NULL,'KAN04','Gordon and Koppel Field','Kansas City','MO','US'),
(108,NULL,'KAN05','Municipal Stadium','Kansas City','MO','US'),
(109,'Royals Stadium','KAN06','Kauffman Stadium','Kansas City','MO','US'),
(110,'Walte''s Pasture','KEO01','Perry Park','Keokuk','IA','US'),
(111,NULL,'LAS01','Cashman Field','Las Vegas','NV','US'),
(112,NULL,'LBV01','The Ballpark at Disney''s Wide World','Lake Buena Vista','FL','US'),
(113,NULL,'LON01','London Stadium','London','ENG','UK'),
(114,NULL,'LOS01','Los Angeles Memorial Coliseum','Los Angeles','CA','US'),
(115,NULL,'LOS02','Wrigley Field','Los Angeles','CA','US'),
(116,'Chavez Ravine','LOS03','Dodger Stadium','Los Angeles','CA','US'),
(117,NULL,'LOU01','Louisville Baseball Park','Louisville','KY','US'),
(118,NULL,'LOU02','Eclipse Park I','Louisville','KY','US'),
(119,NULL,'LOU03','Eclipse Park II','Louisville','KY','US'),
(120,NULL,'LOU04','Eclipse Park III','Louisville','KY','US'),
(121,NULL,'LUD01','Ludlow Baseball Park','Ludlow','KY','US'),
(122,NULL,'MAS01','Long Island Grounds','Maspeth','NY','US'),
(123,'JoeRobbie; ProPlayer; Dolphin; LandShark','MIA01','Sun Life Stadium','Miami','FL','US'),
(124,NULL,'MIA02','Marlins Park','Miami','FL','US'),
(125,NULL,'MID01','Mansfield Club Grounds','Middletown','CT','US'),
(126,NULL,'MIL01','Milwaukee Base-Ball Grounds','Milwaukee','WI','US'),
(127,NULL,'MIL02','Wright Street Grounds','Milwaukee','WI','US'),
(128,NULL,'MIL03','Athletic Park','Milwaukee','WI','US'),
(129,NULL,'MIL04','Lloyd Street Grounds','Milwaukee','WI','US'),
(130,NULL,'MIL05','County Stadium','Milwaukee','WI','US'),
(131,NULL,'MIL06','Miller Park','Milwaukee','WI','US'),
(132,NULL,'MIN01','Athletic Park','Minneapolis','MN','US'),
(133,NULL,'MIN02','Metropolitan Stadium','Bloomington','MN','US'),
(134,NULL,'MIN03','Hubert H. Humphrey Metrodome','Minneapolis','MN','US'),
(135,NULL,'MIN04','Target Field','Minneapolis','MN','US'),
(136,NULL,'MNT01','Estadio Monterrey','Monterrey','Nuevo Leon','MX'),
(137,'Jarry Park','MON01','Parc Jarry','Montreal','QC','CA'),
(138,'Olympic Stadium','MON02','Stade Olympique','Montreal','QC','CA'),
(139,'Brewster Park','NEW01','Howard Avenue Grounds','New Haven','CT','US'),
(140,NULL,'NEW02','Hamilton Park','New Haven','CT','US'),
(141,'Beyerle''s Park','NEW03','Geauga Lake Grounds','Geauga Lake','OH','US'),
(142,NULL,'NWK01','Wiedenmeyer''s Park','Newark','NJ','US'),
(143,NULL,'NYC01','Union Grounds','Brooklyn','NY','US'),
(144,NULL,'NYC02','Capitoline Grounds','Brooklyn','NY','US'),
(145,NULL,'NYC03','Polo Grounds I 
(Southeast Diamond)','New York','NY','US'),
(146,NULL,'NYC04','Polo Grounds II 
(Southwest Diamond)','New York','NY','US'),
(147,NULL,'NYC05','Washington Park I','Brooklyn','NY','US'),
(148,NULL,'NYC06','Metropolitan Park','New York','NY','US'),
(149,'Ridgewood Park I','NYC07','Grauer''s Ridgewood Park','Queens','NY','US'),
(150,NULL,'NYC08','Washington Park II','Brooklyn','NY','US'),
(151,NULL,'NYC09','Polo Grounds III','New York','NY','US'),
(152,NULL,'NYC10','Polo Grounds IV','New York','NY','US'),
(153,NULL,'NYC11','Eastern Park','Brooklyn','NY','US'),
(154,NULL,'NYC12','Washington Park III','Brooklyn','NY','US'),
(155,NULL,'NYC13','Hilltop Park','New York','NY','US'),
(156,NULL,'NYC14','Polo Grounds V','New York','NY','US'),
(157,NULL,'NYC15','Ebbets Field','Brooklyn','NY','US'),
(158,NULL,'NYC16','Yankee Stadium I','New York','NY','US'),
(159,'William A. Shea Stadium','NYC17','Shea Stadium','New York','NY','US'),
(160,'Ridgewood Park II','NYC18','Wallace''s Ridgewood Park','Queens','NY','US'),
(161,NULL,'NYC19','Washington Park IV','Brooklyn','NY','US'),
(162,NULL,'NYC20','Citi Field','New York','NY','US'),
(163,NULL,'NYC21','Yankee Stadium II','New York','NY','US'),
(164,'Network Associates Coliseum','OAK01','Oakland-Alameda County Coliseum','Oakland','CA','US'),
(165,NULL,'OMA01','TD Ameritrade Park','Omaha','NE','US'),
(166,'Pendleton Park','PEN01','East End Park','Cincinnati','OH','US'),
(167,'Athletics Park','PHI01','Jefferson Street Grounds','Philadelphia','PA','US'),
(168,NULL,'PHI02','Centennial Park','Philadelphia','PA','US'),
(169,NULL,'PHI03','Oakdale Park','Philadelphia','PA','US'),
(170,NULL,'PHI04','Recreation Park','Philadelphia','PA','US'),
(171,NULL,'PHI05','Keystone Park','Philadelphia','PA','US'),
(172,NULL,'PHI06','Huntingdon Grounds I','Philadelphia','PA','US'),
(173,NULL,'PHI07','Forepaugh Park','Philadelphia','PA','US'),
(174,NULL,'PHI08','University of Penn. Athletic Field','Philadelphia','PA','US'),
(175,NULL,'PHI09','Baker Bowl','Philadelphia','PA','US'),
(176,NULL,'PHI10','Columbia Park','Philadelphia','PA','US'),
(177,'Connie Mack Stadium','PHI11','Shibe Park','Philadelphia','PA','US'),
(178,NULL,'PHI12','Veterans Stadium','Philadelphia','PA','US'),
(179,NULL,'PHI13','Citizens Bank Park','Philadelphia','PA','US'),
(180,NULL,'PHI14','Huntingdon Grounds II','Philadelphia','PA','US'),
(181,'Bank One Ballpark','PHO01','Chase Field','Phoenix','AZ','US'),
(182,NULL,'PIT01','Union Park','Pittsburgh','PA','US'),
(183,'Lower Field','PIT02','Exposition Park I','Pittsburgh','PA','US'),
(184,'Upper Field','PIT03','Exposition Park II','Pittsburgh','PA','US'),
(185,NULL,'PIT04','Recreation Park','Pittsburgh','PA','US'),
(186,NULL,'PIT05','Exposition Park III','Pittsburgh','PA','US'),
(187,NULL,'PIT06','Forbes Field','Pittsburgh','PA','US'),
(188,NULL,'PIT07','Three Rivers Stadium','Pittsburgh','PA','US'),
(189,NULL,'PIT08','PNC Park','Pittsburgh','PA','US'),
(190,NULL,'PRO01','Adelaide Avenue Grounds','Providence','RI','US'),
(191,NULL,'PRO02','Messer Street Grounds','Providence','RI','US'),
(192,NULL,'RCK01','Agricultural Society Fair Grounds','Rockford','IL','US'),
(193,NULL,'RIC01','Richmond Fair Grounds','Richmond','VA','US'),
(194,NULL,'RIC02','Allens Pasture','Richmond','VA','US'),
(195,NULL,'ROC01','Culver Field I','Rochester','NY','US'),
(196,NULL,'ROC02','Culver Field II','Rochester','NY','US'),
(197,NULL,'ROC03','Ontario Beach Grounds','Rochester','NY','US'),
(198,NULL,'SAI01','St. George Cricket Grounds','New York','NY','US'),
(199,'San Diego/Jack Murphy Stadium','SAN01','Qualcomm Stadium','San Diego','CA','US'),
(200,NULL,'SAN02','PETCO Park','San Diego','CA','US'),
(201,NULL,'SEA01','Sick''s Stadium','Seattle','WA','US'),
(202,NULL,'SEA02','Kingdome','Seattle','WA','US'),
(203,'T-Mobile Park','SEA03','Safeco Field','Seattle','WA','US'),
(204,NULL,'SFO01','Seals Stadium','San Francisco','CA','US'),
(205,'3Com Park','SFO02','Candlestick Park','San Francisco','CA','US'),
(206,'Pacific Bell Park; SBC Park','SFO03','AT&T Park','San Francisco','CA','US'),
(207,NULL,'SJU01','Estadio Hiram Bithorn','San Juan',NULL,'PR'),
(208,'Springfield Track','SPR01','Hampden Park Race Track','Springfield','MA','US'),
(209,NULL,'STL01','Red Stockings Base Ball Park','St. Louis','MO','US'),
(210,NULL,'STL02','Grand Avenue Park','St. Louis','MO','US'),
(211,NULL,'STL03','Sportsman''s Park I','St. Louis','MO','US'),
(212,NULL,'STL04','Union Grounds','St. Louis','MO','US'),
(213,NULL,'STL05','Robison Field','St. Louis','MO','US'),
(214,NULL,'STL06','Sportsman''s Park II','St. Louis','MO','US'),
(215,'Busch Stadium I','STL07','Sportsman''s Park III','St. Louis','MO','US'),
(216,'Federal League Park','STL08','Handlan''s Park','St. Louis','MO','US'),
(217,NULL,'STL09','Busch Stadium II','St. Louis','MO','US'),
(218,NULL,'STL10','Busch Stadium III','St. Louis','MO','US'),
(219,NULL,'STP01','Tropicana Field','St. Petersburg','FL','US'),
(220,NULL,'SYD01','Sydney Cricket Ground','Sydney','New South Wales','AU'),
(221,'Newell Park','SYR01','Star Park I','Syracuse','NY','US'),
(222,NULL,'SYR02','Star Park II','Syracuse','NY','US'),
(223,NULL,'SYR03','Iron Pier','Syracuse','NY','US'),
(224,NULL,'THR01','Three Rivers Park','Three Rivers','NY','US'),
(225,NULL,'TOK01','Tokyo Dome','Tokyo','Tokyo','JP'),
(226,NULL,'TOL01','League Park','Toledo','OH','US'),
(227,NULL,'TOL02','Tri-State Fair Grounds','Toledo','OH','US'),
(228,NULL,'TOL03','Speranza Park','Toledo','OH','US'),
(229,NULL,'TOL04','Armory Park','Toledo','OH','US'),
(230,NULL,'TOR01','Exhibition Stadium','Toronto','ON','CA'),
(231,'Skydome','TOR02','Rogers Centre','Toronto','ON','CA'),
(232,NULL,'TRO01','Haymakers'' Grounds','Troy','NY','US'),
(233,NULL,'TRO02','Putnam Grounds','Troy','NY','US'),
(234,NULL,'WAR01','Rocky Point Park','Warwick','RI','US'),
(235,NULL,'WAS01','Olympic Grounds','Washington','DC','US'),
(236,NULL,'WAS02','National Grounds','Washington','DC','US'),
(237,NULL,'WAS03','Capitol Grounds','Washington','DC','US'),
(238,NULL,'WAS04','Athletic Park','Washington','DC','US'),
(239,NULL,'WAS05','Swampoodle Grounds','Washington','DC','US'),
(240,NULL,'WAS06','Boundary Field','Washington','DC','US'),
(241,NULL,'WAS07','American League Park I','Washington','DC','US'),
(242,NULL,'WAS08','American League Park II','Washington','DC','US'),
(243,NULL,'WAS09','Griffith Stadium','Washington','DC','US'),
(244,'D.C. Stadium','WAS10','Robert F. Kennedy Stadium','Washington','DC','US'),
(245,NULL,'WAS11','Nationals Park','Washington','DC','US'),
(246,NULL,'WAT01','Troy Ball Club Grounds','Watervliet','NY','US'),
(247,NULL,'WAV01','Waverly Fairgrounds','Waverly','NJ','US'),
(248,NULL,'WEE01','Monitor Grounds','Weehawken','NJ','US'),
(249,NULL,'WHE01','Island Grounds','Wheeling','WV','US'),
(250,NULL,'WIL01','Union Street Park','Wilmington','DE','US'),
(251,NULL,'WIL02','BB&T Ballpark at Bowman Field','Williamsport','PA','US'),
(252,NULL,'WNY01','West New York Field Club Grounds','West New York','NJ','US'),
(253,NULL,'WOR01','Agricultural County Fair Grounds I','Worcester','MA','US'),
(254,NULL,'WOR02','Agricultural County Fair Grounds II','Worcester','MA','US'),
(255,NULL,'WOR03','Worcester Driving Park Grounds','Worcester','MA','US');