INSERT INTO Franchise VALUES 
(1,'ALT','Altoona Mountain City','N',NULL),
(2,'ANA','Los Angeles Angels of Anaheim','Y',NULL),
(3,'ARI','Arizona Diamondbacks','Y',NULL),
(4,'ATH','Philadelphia Athletics','N','PNA'),
(5,'ATL','Atlanta Braves','Y','BNA'),
(6,'BAL','Baltimore Orioles','Y',NULL),
(7,'BFB','Buffalo Bisons','N',NULL),
(8,'BFL','Buffalo Bisons','N',NULL),
(9,'BLC','Baltimore Canaries',NULL,NULL),
(10,'BLO','Baltimore Orioles','N',NULL),
(11,'BLT','Baltimore Terrapins','N',NULL),
(12,'BLU','Baltimore Monumentals','N',NULL),
(13,'BNA','Boston Red Stockings',NULL,'ATL'),
(14,'BOS','Boston Red Sox','Y',NULL),
(15,'BRA','Brooklyn Atlantics',NULL,NULL),
(16,'BRD','Boston Reds','N',NULL),
(17,'BRG','Brooklyn Gladiators','N',NULL),
(18,'BRS','Boston Reds','N',NULL),
(19,'BTT','Brooklyn Tip-Tops','N',NULL),
(20,'BUF','Buffalo Bisons','N',NULL),
(21,'BWW','Brooklyn Ward''s Wonders','N',NULL),
(22,'CBK','Columbus Buckeyes','N',NULL),
(23,'CBL','Cleveland Blues','N',NULL),
(24,'CEN','Philadelphia Centennials',NULL,NULL),
(25,'CFC','Cleveland Forest Citys',NULL,NULL),
(26,'CHC','Chicago Cubs','Y','CNA'),
(27,'CHH','Chicago Whales','N',NULL),
(28,'CHP','Chicago Pirates','N',NULL),
(29,'CHW','Chicago White Sox','Y',NULL),
(30,'CIN','Cincinnati Reds','Y',NULL),
(31,'CKK','Cincinnati Kelly''s Killers','N',NULL),
(32,'CLE','Cleveland Indians','Y',NULL),
(33,'CLI','Cleveland Infants','N',NULL),
(34,'CLS','Columbus Solons','N',NULL),
(35,'CLV','Cleveland Spiders','N',NULL),
(36,'CNA','Chicago White Stockings',NULL,'CHC'),
(37,'CNR','Cincinnati Reds','N',NULL),
(38,'COL','Colorado Rockies','Y',NULL),
(39,'COR','Cincinnati Outlaw Reds','N',NULL),
(40,'CPI','Chicago/Pittsburgh (Union League)','N',NULL),
(41,'DET','Detroit Tigers','Y',NULL),
(42,'DTN','Detroit Wolverines','N',NULL),
(43,'ECK','Brooklyn Eckfords',NULL,NULL),
(44,'FLA','Florida Marlins','Y',NULL),
(45,'HAR','Hartford Dark Blues','N','HNA'),
(46,'HNA','Hartford Dark Blues',NULL,'HAR'),
(47,'HOU','Houston Astros','Y',NULL),
(48,'IBL','Indianapolis Blues','N',NULL),
(49,'IHO','Indianapolis Hoosiers','N',NULL),
(50,'IND','Indianapolis Hoosiers','N',NULL),
(51,'KCC','Kansas City Cowboys','N',NULL),
(52,'KCN','Kansas City Cowboys','N',NULL),
(53,'KCP','Kansas City Packers','N',NULL),
(54,'KCR','Kansas City Royals','Y',NULL),
(55,'KCU','Kansas City Cowboys','N',NULL),
(56,'KEK','Fort Wayne Kekiongas',NULL,NULL),
(57,'LAD','Los Angeles Dodgers','Y',NULL),
(58,'LGR','Louisville Grays','N',NULL),
(59,'LOU','Louisville Colonels','N',NULL),
(60,'MAN','Middletown Mansfields',NULL,NULL),
(61,'MAR','Baltimore Marylands',NULL,NULL),
(62,'MIL','Milwaukee Brewers','Y',NULL),
(63,'MIN','Minnesota Twins','Y',NULL),
(64,'MLA','Milwaukee Brewers','N',NULL),
(65,'MLG','Milwaukee Grays','N',NULL),
(66,'MLU','Milwaukee Brewers','N',NULL),
(67,'NAT','Washington Nationals',NULL,NULL),
(68,'NEW','Newark Pepper','N',NULL),
(69,'NHV','New Haven Elm Citys',NULL,NULL),
(70,'NNA','New York Mutuals',NULL,'NYU'),
(71,'NYI','New York Giants','N',NULL),
(72,'NYM','New York Mets','Y',NULL),
(73,'NYP','New York Metropolitans','N',NULL),
(74,'NYU','New York Mutuals','N','NNA'),
(75,'NYY','New York Yankees','Y',NULL),
(76,'OAK','Oakland Athletics','Y',NULL),
(77,'OLY','Washington Olympics',NULL,NULL),
(78,'PBB','Pittsburgh Burghers','N',NULL),
(79,'PBS','Pittsburgh Rebels','N',NULL),
(80,'PHA','Philadelphia Athletics','N',NULL),
(81,'PHI','Philadelphia Phillies','Y',NULL),
(82,'PHK','Philadelphia Keystones','N',NULL),
(83,'PHQ','Philadelphia Athletics','N',NULL),
(84,'PIT','Pittsburgh Pirates','Y',NULL),
(85,'PNA','Philadelphia Athletics',NULL,'ATH'),
(86,'PRO','Providence Grays','N',NULL),
(87,'PWS','Philadelphia White Stockings',NULL,NULL),
(88,'RES','Elizabeth Resolutes',NULL,NULL),
(89,'RIC','Richmond Virginians','N',NULL),
(90,'ROC','Rochester Broncos','N',NULL),
(91,'ROK','Rockford Forest Citys',NULL,NULL),
(92,'SBS','St. Louis Brown Stockings','N','SNA'),
(93,'SDP','San Diego Padres','Y',NULL),
(94,'SEA','Seattle Mariners','Y',NULL),
(95,'SFG','San Francisco Giants','Y',NULL),
(96,'SLI','St. Louis Terriers','N',NULL),
(97,'SLM','St. Louis Maroons','N',NULL),
(98,'SLR','St. Louis Red Stockings',NULL,NULL),
(99,'SNA','St. Louis Brown Stockings',NULL,'SBS'),
(100,'STL','St. Louis Cardinals','Y',NULL),
(101,'STP','St. Paul Apostles','N',NULL),
(102,'SYR','Syracuse Stars','N',NULL),
(103,'SYS','Syracuse Stars','N',NULL),
(104,'TBD','Tampa Bay Rays','Y',NULL),
(105,'TEX','Texas Rangers','Y',NULL),
(106,'TLM','Toledo Maumees','N',NULL),
(107,'TOL','Toledo Blue Stockings','N',NULL),
(108,'TOR','Toronto Blue Jays','Y',NULL),
(109,'TRO','Troy Haymakers',NULL,NULL),
(110,'TRT','Troy Trojans','N',NULL),
(111,'WAS','Washington Senators','N',NULL),
(112,'WBL','Washington Blue Legs',NULL,NULL),
(113,'WES','Keokuk Westerns',NULL,NULL),
(114,'WIL','Wilmington Quicksteps','N',NULL),
(115,'WNA','Washington Nationals','N',NULL),
(116,'WNL','Washington Nationals','N',NULL),
(117,'WNT','Washington Nationals',NULL,NULL),
(118,'WOR','Worcester Ruby Legs','N',NULL),
(119,'WSN','Washington Nationals','Y',NULL),
(120,'WST','Washington Statesmen','N',NULL);